name: PrototypeLab
description: PL's test laboratory for non-sim projects
version: 0.0.1
homepage: https://github.com/FarragoFiction/PrototypeLab
author: paradoxLands

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git
  TextEngine:
    git: git://github.com/FarragoFiction/TextEngine.git

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
