name: PrototypeLab
description: PL's test laboratory for non-sim projects
version: 2.2.0
homepage: https://github.com/FarragoFiction/PrototypeLab
author: paradoxLands

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  CommonLib:
    git:
      url: git://github.com/FarragoFiction/CommonLib.git
      ref: worker
  #LoaderLib:
  #  git: git://github.com/FarragoFiction/LoaderLib.git
  #TextEngine:
  #  git: git://github.com/FarragoFiction/TextEngine.git

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: any

web:
  compiler:
    debug: dartdevc
