name: PrototypeLab
description: PL's test laboratory for non-sim projects
version: 2.12.0
homepage: https://github.com/FarragoFiction/PrototypeLab
author: paradoxLands
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git
  TextEngine:
    git: git://github.com/FarragoFiction/TextEngine.git

dev_dependencies:
  build: any
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  build_config: any
  test: any
  glob: any
  path: any

